[2025-04-01T01:26:37.285+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T01:26:37.672+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2-Cargar_data.load_data manual__2025-04-01T01:26:20.916309+00:00 [queued]>
[2025-04-01T01:26:37.716+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2-Cargar_data.load_data manual__2025-04-01T01:26:20.916309+00:00 [queued]>
[2025-04-01T01:26:37.717+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T01:26:37.761+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 01:26:20.916309+00:00
[2025-04-01T01:26:37.794+0000] {standard_task_runner.py:72} INFO - Started process 826 to run task
[2025-04-01T01:26:37.822+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '2-Cargar_data', 'load_data', 'manual__2025-04-01T01:26:20.916309+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/Cargar_datos.py', '--cfg-path', '/tmp/tmpuhndyshg']
[2025-04-01T01:26:37.852+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask load_data
[2025-04-01T01:26:38.032+0000] {task_command.py:467} INFO - Running <TaskInstance: 2-Cargar_data.load_data manual__2025-04-01T01:26:20.916309+00:00 [running]> on host 7ed3aa8fcef8
[2025-04-01T01:26:38.233+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2-Cargar_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T01:26:20.916309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T01:26:20.916309+00:00'
[2025-04-01T01:26:38.237+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T01:26:38.298+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-01T01:26:38.343+0000] {logging_mixin.py:190} INFO - Ejecutando iteración 0
[2025-04-01T01:26:38.390+0000] {logging_mixin.py:190} INFO - {"detail":"Número de grupo inválido"}
[2025-04-01T01:26:38.392+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/Cargar_datos.py", line 84, in load_data
    df = pd.DataFrame(data["data"], columns=[
KeyError: 'data'
[2025-04-01T01:26:38.434+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=2-Cargar_data, task_id=load_data, run_id=manual__2025-04-01T01:26:20.916309+00:00, execution_date=20250401T012620, start_date=20250401T012637, end_date=20250401T012638
[2025-04-01T01:26:38.583+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T01:26:38.584+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task load_data ('data'; 826)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/Cargar_datos.py", line 84, in load_data
    df = pd.DataFrame(data["data"], columns=[
KeyError: 'data'
[2025-04-01T01:26:38.642+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-01T01:26:38.726+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T01:26:38.736+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
