[2025-03-09T00:16:14.413+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_penguins_data.preprocess_data manual__2025-03-09T00:16:12.684472+00:00 [queued]>
[2025-03-09T00:16:14.419+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_penguins_data.preprocess_data manual__2025-03-09T00:16:12.684472+00:00 [queued]>
[2025-03-09T00:16:14.419+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-09T00:16:14.427+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-03-09 00:16:12.684472+00:00
[2025-03-09T00:16:14.430+0000] {standard_task_runner.py:57} INFO - Started process 286 to run task
[2025-03-09T00:16:14.433+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocess_penguins_data', 'preprocess_data', 'manual__2025-03-09T00:16:12.684472+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/Procesa_data.py', '--cfg-path', '/tmp/tmp7js32had']
[2025-03-09T00:16:14.434+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask preprocess_data
[2025-03-09T00:16:14.469+0000] {task_command.py:410} INFO - Running <TaskInstance: preprocess_penguins_data.preprocess_data manual__2025-03-09T00:16:12.684472+00:00 [running]> on host de40e2ed39bc
[2025-03-09T00:16:14.516+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_penguins_data' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T00:16:12.684472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T00:16:12.684472+00:00'
[2025-03-09T00:16:14.619+0000] {xcom.py:640} ERROR - Object of type Series is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-03-09T00:16:14.620+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Procesa_data.py", line 104, in preprocess_data
    ti.xcom_push(key='y_train', value=y_train)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2384, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2025-03-09T00:16:14.625+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocess_penguins_data, task_id=preprocess_data, execution_date=20250309T001612, start_date=20250309T001614, end_date=20250309T001614
[2025-03-09T00:16:14.633+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task preprocess_data (Object of type Series is not JSON serializable; 286)
[2025-03-09T00:16:14.645+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-09T00:16:14.660+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
