[2025-03-08T22:59:17.607+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: delete_penguins_db.drop_penguins_table manual__2025-03-08T22:59:16.830983+00:00 [queued]>
[2025-03-08T22:59:17.613+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: delete_penguins_db.drop_penguins_table manual__2025-03-08T22:59:16.830983+00:00 [queued]>
[2025-03-08T22:59:17.613+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-08T22:59:17.622+0000] {taskinstance.py:1350} INFO - Executing <Task(MySqlOperator): drop_penguins_table> on 2025-03-08 22:59:16.830983+00:00
[2025-03-08T22:59:17.624+0000] {standard_task_runner.py:57} INFO - Started process 125 to run task
[2025-03-08T22:59:17.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'delete_penguins_db', 'drop_penguins_table', 'manual__2025-03-08T22:59:16.830983+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/Borrar_datos.py', '--cfg-path', '/tmp/tmpe7tpgz1s']
[2025-03-08T22:59:17.626+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask drop_penguins_table
[2025-03-08T22:59:17.657+0000] {task_command.py:410} INFO - Running <TaskInstance: delete_penguins_db.drop_penguins_table manual__2025-03-08T22:59:16.830983+00:00 [running]> on host 35d6ef7d8b81
[2025-03-08T22:59:17.700+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='delete_penguins_db' AIRFLOW_CTX_TASK_ID='drop_penguins_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T22:59:16.830983+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-08T22:59:16.830983+00:00'
[2025-03-08T22:59:17.700+0000] {sql.py:262} INFO - Executing: 
USE ***_db;
DROP TABLE IF EXISTS penguins;
[2025-03-08T22:59:17.711+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_default` isn't defined
[2025-03-08T22:59:17.713+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=delete_penguins_db, task_id=drop_penguins_table, execution_date=20250308T225916, start_date=20250308T225917, end_date=20250308T225917
[2025-03-08T22:59:17.720+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 31 for task drop_penguins_table (The conn_id `mysql_default` isn't defined; 125)
[2025-03-08T22:59:17.757+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-08T22:59:17.770+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
